In [6]:
import pandas as pd

df = pd.read_csv('../data/tweet_clean.csv')
text = pd.

In [8]:
df['link_free_without_emoji'][0]

'[\'In A Promised Land, I talk about the decisions I had to make during the first few years of my presidency. Here are some thoughts on how I approach tough questions: \', " With COVID-19 cases reaching an all-time high this week, we\'ve got to continue to do our part to protect one another. This pandemic is far from over and your actions can help save lives. ", \' To all of you in Georgia, today is the last day to register to vote in the upcoming runoff election. Take a few minutes right now to register to vote, and then make sure everybody you know is registered, too. \', \' Thanks for sharing Marjon. I hope you get something out of A Promised Land – keep up the good work! \', \' Glad to see A Promised Land in such good company. \', " If you\'re in Georgia, make sure you and everybody you know is registered to vote by Monday, December 7. And if you turn 18 by January 5, you\'re eligible to vote in the runoff. Get registered right now: ", \' Join me for a conversation with the next U.

---------------------------

### RF takes in a chunk of sentences within a list, with sentences wrapped in a string

In [1]:
text = """ 
🥨🥨🥨
Prezel heart
I can’t spell prezel lol
Didnt spend my childhood time with Disney channel
I researched her
And still no idea who she is
I hope you guys stay safe. I read the email about the two new cases on campus😭😭😭
wowwwww
Its like the Charlie’s chocolate factory invitation
So cool
ohhhhhh
Hahahahahahahahahahahahahahahahaha
Wait, I thought Davis is the UWC founder Davis
Hes related to New Balance?
wait
I always think the Davis library is donated by UWC davis
New Balance Davis is our alum??
Oh wow
But I’m not going to boycott Davis Library
Lol
hahahahahahahaha
Can you explain the story for me please
We are designing a product that helps analyze people’s personality based on their chatting history
And advise how to chat to better the relationship
hahahahahahaha
And after we have the product, you guys should try
lol
Just for fun
And it’s English
To see what mbti of the person you are chatting with
You upload the chat history to our prodcut
also
If you provide his or her phone number, we could scrape their social media account to tell the MBTI as well
We only got two weeks
I think we are going to have the basic model and then fine tuning it
If we got extra time
We are gonna fix this problem
We got four weeks left
But we havnet finished the lecturing
Im not enrolled in the fall, so I’m not encluded in the Jterm
And we met a networking event
We didnt talk too much
But im asking if he wanna out for a coffee chat?
Like im using this coffee chat as an excuse
So we can meet offline
I don’t wanna chat online
This is the whole story: I met him on a networking event. We’ve talked a little bit but not a lot.
And I want to meet him in person
Like im intereted in what he does and also him
He said that he’s usually in office, and can’t really come out, but we could find a time to call
But I don’t want to call him
I want to meet him
update: I said yes to his call
Because he’s actually think I want to network with him
My parents want me to get prepared
They want me to go to grad school
Ohhh so you are not planning to go to grad school right after college
My parents want me to go right after
But I don’t
Want to
no
https://t.co/5pSRmD2rLF
I truly don’t think I got the talent in physics
And I don’t want to be a researcher in the lab
I hate labs
That’s the problem
I don’t know
But my parents think the name is important
And also if I want to come back to China to work
I have to go to a famous college for grad school
Firms in china prefer those have a master degree
Im SOOOOOOOO BADDDDD at standardized testing
What did you get at the sat?
I took me four times to get 1500
Happy thanksgiving!!!!
Hope to see you guys this coming fall
I actually highly recommend the data science class
It looks really practical
A really nice touch on the resume I will say
However, I don’t know how much you guys can learn in one month though
But just saying, machine learning isn’t hard and does not require much coding
Same thing for deep learning
The hardest part is cleaning the data, which requires a lot of coding
Like A LOT
But im pretty sure you guys will learn machine learning
Without machine learning, it is not data science anymore
It is
But good for your future
I kind of want to audit the machine learning in the spring
😭
But just audit?
Oh my
I follow his youruve
And he got like millions of followers
"""

In [94]:
text_1 = '''Brenda when do you wanna start drinking 🍻 
Like 10?
And cunthia the ice is in the freezer in a cup 
Oh... 😹 idk because I think patty and Christian are sleeping ...? 
Is that fine?
Should I go now 
I have bad service outside 
Brendaaaa 
We have the ice 
Now?
For real 
Where are we going 
Oh omg 
Brunch 12 and not 10:30
I was like img she wants to get brunch so early 
Bro I just woke up can we meet 12:15
Proc? 
Take your time I still need to get dressed 😄
LOL just come to the suite 😹
Oh wiat can you get in
Let me hurry up
Is anyone doing later today
LOL I forgot to include hw
Yeah we’re in Monroe 
Kk and yeah we saw ! 
Yesterday my friend went to a party where there were like 60 people ...
Yes 
Cynthia you’re in the suite right 
Please tell me you are 
She was really famous like in 2010 or something 😹😹
My professor said soon .... uhhh ...
I AM PREGNANT
WITH TRIPLETS
THE AUDACITY THIS MAN HAS
omg i only meant to send that to BRENDA lolol omg no
I KNOW LIKE OML 🤤🤤🤤
but also stay in your lane sis 🙄
aka far away from thirsting over JK
MISS MA’AM IF YOU DONT STOP
Cynthia are you awake ...?
No Brenda I was asleep 🙄 since 1
Yeah it was perfect! Sorry hehehe 
Does anyone wanna get lunch with me at 12:30 lmk
Brenda I’m gonna start packing tonight, when can I pick up the alcohol and shot glass I have in your room 🧐
probably will stop by tonight around 8 or 9 if that works
Cynthia can I use the tape 
Are you in your room? 
K thanks !
Did you just take the picture from
The meme ? 
I’m confused 
But I think she just used the picture from Elisa Rodriguez ? 
Not y’all believing her lol
LOL
That’s embarrassing luv 
Can never trick a Scorpio 
Anyone wanna go to the grille 
Whenever ... 
Okay🥰
Ready whenever you are 🥰
Lunch  anyone ?
When do you wanna go
Coking 
Coming 
Cynthia do you know how to make hot chocolate from a chocolate bar 
Just one re  go all sized one ? 
Milk chocolate ? 
And we should make it in the proc basement kitchen 
What should we get cunthia ! 
We are at Midd x 
How much though 
We’ll meet you in giff basement kitchen in like 5 minutes ? Can you bring a pot...? I packed mine 😁
We are here now 😁
Cynthia when will you be awake tomorrow so I can give you my things
Perfect ! 
Sweet dreams 
Don’t forget to steam life goes on 😁
I was saying sweet dreams to you 
How could I sleep with BTS COMEBACK
Yeah that would never be me 
Listen to it! Very healing and beautiful 🥺
14 MINUTES
NOT HOURS
Lol ? 
😭
Thank you 
I know 
🥺
🥰
It’s so beautiful 🥺
And comforting 
I love them 
I’m sure no one noticed 
POV YOURE MY FAN AND YOU SEE MY AT THE AIRPORT
BUT YOURE TOO INTIMIDATED BY MY STAR POWER TO APPROACH ME AND ASK FOR A PICTURE 
*ME
It’s from that angle because my fans are beneath me 
Beneath me as in I’m better and superior ... not short 
The guy next to me is so cute 
Also please don’t forget Cooky 🥰🥰
Okay uwuwuwuww thank you 
Goodbye forever 🥰🥰'''

In [51]:
import re

def deEmojify(text):
    regrex_pattern = re.compile(pattern = "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags = re.UNICODE)
    return regrex_pattern.sub(r'',text)

In [52]:
deEmojify = deEmojify(text).split('\n')

In [53]:
def remove_links(post_split):
    # split each post into a list of individual words
    post_split_split = [x.split(' ') for x in post_split]
    
    # removes any 'words' that have http:// or https:// in them
    return_list = [[item for item in sentence if ('http://' not in item and 'https://' not in item)] for sentence in post_split_split]
    
    # returns a list of posts if they are not empty after removing the links
    return [' '.join(sentence) for sentence in return_list if sentence]

In [56]:
text = remove_links(deEmojify)

In [55]:
def sentence_count(post):
    return len(post)

def word_count(post):
    count = 0
    for sentence in post:
        count += len(sentence.split())
    return count

In [58]:
sentence_count(text)
word_count(text)

642

In [59]:
def avg_word_length(posts_split):
    word_length_count = []
    count = 0
    for post in posts_split:
        count += len(post)  
    return count

In [60]:
avg_word_length(text)

3203

# Final PreProcess

In [2]:
#deEmojify the text
import re

def deEmojify(text):
    regrex_pattern = re.compile(pattern = "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags = re.UNICODE)
    return regrex_pattern.sub(r'',text)

In [3]:
def remove_links(post_split):
    # split each post into a list of individual words
    post_split_split = [x.split(' ') for x in post_split]
    
    # removes any 'words' that have http:// or https:// in them
    return_list = [[item for item in sentence if ('http://' not in item and 'https://' not in item)] for sentence in post_split_split]
    
    # returns a list of posts if they are not empty after removing the links
    return [' '.join(sentence) for sentence in return_list if sentence]

In [4]:
import syllables

def sentence_count(post):
    return len(post)

def word_count(post):
    count = 0
    for sentence in post:
        count += len(sentence.split())
    return count

def syll_count(X):
    count_syll = 0
    syll_count_ls = []
    for sentence in X:
        sentence = sentence.split()
        for word in sentence:
            count_syll +=  syllables.estimate(word)
        syll_count_ls.append(count_syll)
    return count_syll

In [5]:
def word_length_count(posts_split):
    word_length_count = []
    count = 0
    for post in posts_split:
        count += len(post)  
    return count

In [6]:
from collections import Counter

def count_unique_word(posts):
    count_unique = len(Counter(posts))
    return count_unique

In [7]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

def VAD(posts):
    analyzer = SentimentIntensityAnalyzer()
    return analyzer.polarity_scores(posts)

In [8]:
from nrclex import NRCLex

def NRC_emotion(posts):
    emotion = NRCLex(posts)
    return emotion.affect_frequencies

In [9]:
import pickle
word_count_scaler = pickle.load(open('../notebooks/models/word_count_scaler', 'rb'))
unique_word_scaler = pickle.load(open('../notebooks/models/unique_word_scaler', 'rb'))
word_length_scaler = pickle.load(open('../notebooks/models/word_length_scaler', 'rb'))
sentence_count_scaler = pickle.load(open('../notebooks/models/sentence_count_scaler', 'rb'))   
syll_count_scaler = pickle.load(open('../notebooks/models/syll_count_scaler', 'rb'))

In [10]:
import numpy as np

In [102]:
def preprocess(text):

    #deEmojigy and split the text into list of sentences
    text = deEmojify(text).split('\n')
    
    #remove links
    text = remove_links(text)
    
    #word, sentence,etc. count and scaled
    word_count_scaled = word_count_scaler.transform(np.array(word_count(text)).reshape(-1,1))
    count_unique_word_scaled = unique_word_scaler.transform(np.array(count_unique_word(text)).reshape(-1,1))
    word_length_count_scaled = word_length_scaler.transform(np.array(word_length_count(text)).reshape(-1,1))
    sentence_count_scaled = sentence_count_scaler.transform(np.array(sentence_count(text)).reshape(-1,1))
    syll_count_scaled = syll_count_scaler.transform(np.array(syll_count(text)).reshape(-1,1)) 

    
    #word_per_sentence
    avg_word_length = word_length_count_scaled/word_count_scaled
    word_per_sentence = word_count_scaled/sentence_count_scaled
    
    #TTR
    TTR = count_unique_word_scaled/word_count_scaled
    
    #join all the sentences together and then VAD them
    text_joined = ''.join(text)
    VAD_dict = VAD(text_joined)
    
    #NRC emotion
    emotion_dict = NRC_emotion(text_joined)
    
    #map the VAD and NRC emotion
    neg_sentiment = VAD_dict['neg']
    pos_sentiment = VAD_dict['pos']
    compound_sentiment = VAD_dict['compound']
    neu_sentiment = VAD_dict['neu']
    
    fear = emotion_dict['fear']
    anger = emotion_dict['anger']
    anticip = emotion_dict['anticip']
    trust = emotion_dict['trust']
    surprise = emotion_dict['surprise']
    positive = emotion_dict['positive']
    negative = emotion_dict['negative']
    sadness = emotion_dict['sadness']
    disgust = emotion_dict['disgust']
    joy = emotion_dict['joy']
    
    input_ls = np.array([neg_sentiment,
                neu_sentiment,
                pos_sentiment,
                compound_sentiment,
                fear,
                anger,
                anticip,
                trust,
                surprise,
                positive,
                negative,
                sadness,
                disgust,
                joy,
                float(syll_count_scaled),
                float(word_count_scaled),
                float(count_unique_word_scaled),
                float(word_length_count_scaled),
                float(sentence_count_scaled),
                float(TTR),
                float(avg_word_length),
                float(word_per_sentence_scaled)])
    return input_ls.reshape(-1,21)

In [95]:
processed_text = preprocess(text_1)

In [96]:
processed_text

array([[ 0.055     ,  0.801     ,  0.144     ,  0.9948    ,  0.07407407,
         0.03703704,  0.        ,  0.13580247,  0.03703704,  0.2345679 ,
         0.13580247,  0.07407407,  0.01234568,  0.12345679, -1.83465356,
        -2.14948012, -2.97568242,  1.66844419, -2.97568242,  1.38437308,
        -0.77620824]])

In [97]:
ei_model = pickle.load(open('../notebooks/models/RF_IE_Model_2.0', 'rb'))
jp_model = pickle.load(open('../notebooks/models/RF_JP_Model_2.0', 'rb'))
ns_model = pickle.load(open('../notebooks/models/RF_NS_Model_2.0', 'rb'))
tf_model = pickle.load(open('../notebooks/models/RF_TF_Model_2.0', 'rb'))

In [98]:
ei_model.predict(processed_text)

array([1])

In [99]:
jp_model.predict(processed_text)

array([0])

In [100]:
ns_model.predict(processed_text)

array([1])

In [101]:
tf_model.predict(processed_text)

array([0])